// export const THRESOLD_PERCENTAGE = {
//     high: 50,
//     med: 25,
//     low: 10
// }

export const COMMON_MATRICS = [
    "date",
    "attributedSalesSameSku1d",
    "attributedSalesSameSku7d",
    "attributedSalesSameSku14d",
    "attributedSalesSameSku30d",

    "unitsSoldClicks1d",
    "unitsSoldClicks7d",
    "unitsSoldClicks14d",
    "unitsSoldClicks30d",

    "sales1d",
    "sales7d",
    "sales14d",
    "sales30d",

    "purchases7d",
    "purchases14d",

    "impressions",
    "clicks",
    "cost",
];

export const CAMPAIGN_MATRICS = [
    ...COMMON_MATRICS,
    "campaignBiddingStrategy",
    "roasClicks14d",
    "addToList",
    "purchasesSameSku14d",
    "kindleEditionNormalizedPagesRoyalties14d",
    "purchasesSameSku1d",
    "unitsSoldSameSku1d",
    "purchases1d",
    "purchasesSameSku7d",
    "unitsSoldSameSku7d",
    "costPerClick",
    "retailer",
    "clickThroughRate",
    "kindleEditionNormalizedPagesRead14d",
    "purchasesSameSku30d",
    "qualifiedBorrows",
    "acosClicks14d",
    "purchases30d",
    "unitsSoldSameSku14d",
    "campaignRuleBasedBudgetAmount",
    "campaignBudgetCurrencyCode",
    "campaignId",
    "campaignApplicableBudgetRuleId",
    "campaignBudgetType",
    "topOfSearchImpressionShare",
    "campaignStatus",
    "campaignName",
    "campaignApplicableBudgetRuleName",
    "campaignBudgetAmount",
];


export const ADGROUP_MATRICS = [
    ...COMMON_MATRICS,
    // 'impressions',
    'addToList',
    'qualifiedBorrows',
    'royaltyQualifiedBorrows',
    // 'clicks', 'cost',
    // 'purchases1d',
    // 'purchases7d',
    // 'purchases14d',
    // 'purchases30d',
    'purchasesSameSku1d',
    'purchasesSameSku7d',
    'purchasesSameSku14d',
    'purchasesSameSku30d',
    // 'unitsSoldClicks1d',
    // 'unitsSoldClicks7d',
    // 'unitsSoldClicks14d',
    // 'unitsSoldClicks30d',
    // 'sales1d', 'sales7d',
    // 'sales14d', 'sales30d',
    // 'attributedSalesSameSku1d',
    // 'attributedSalesSameSku7d',
    // 'attributedSalesSameSku14d',
    // 'attributedSalesSameSku30d',
    'unitsSoldSameSku1d',
    'unitsSoldSameSku7d',
    'unitsSoldSameSku14d',
    'unitsSoldSameSku30d',
    'kindleEditionNormalizedPagesRead14d',
    'kindleEditionNormalizedPagesRoyalties14d',
    'campaignBiddingStrategy',
    'costPerClick', 'clickThroughRate',
];



export const KEYWORD_MATRICS = [
    ...COMMON_MATRICS,
    "currency",
    "keywordId",
    "keyword",
    "matchType",
    "topOfSearchImpressionShare"
]

export const SEARCH_TERM_MATRICS = [
    ...COMMON_MATRICS,
    "roasClicks14d",
    "matchType",
    "unitsSoldOtherSku14d",
    "salesOtherSku14d",
    "kindleEditionNormalizedPagesRoyalties14d",
    "searchTerm",
    "unitsSoldSameSku1d",
    "campaignStatus",
    "keyword",
    "purchasesSameSku7d",
    "salesOtherSku7d",
    "campaignBudgetAmount",
    "purchases1d",
    "unitsSoldSameSku30d",
    "costPerClick",
    "adGroupName",
    "campaignId",
    "clickThroughRate",
    "purchaseClickRate14d",
    "kindleEditionNormalizedPagesRead14d",
    "qualifiedBorrows",
    "acosClicks14d",
    "campaignBudgetCurrencyCode",
    "portfolioId",
    "unitsSoldSameSku14d",
    "roasClicks7d",
    "keywordId",
    "royaltyQualifiedBorrows",
    "adGroupId",
    "addToList",
    "keywordBid",
    "targeting",
    "purchasesSameSku14d",
    "unitsSoldOtherSku7d",
    "purchasesSameSku1d",
    "campaignBudgetType",
    "keywordType",
    "purchases30d",
    "unitsSoldSameSku7d",
    "purchasesSameSku30d",
    "campaignName",
    "acosClicks7d",
    "adKeywordStatus"
];


export const TARGETING_MATRICS = [
    ...COMMON_MATRICS,
    "addToList",
    "qualifiedBorrows",
    "royaltyQualifiedBorrows",
    "costPerClick",
    "clickThroughRate",
    "purchases1d",
    "purchases30d",
    "purchasesSameSku1d",
    "purchasesSameSku7d",
    "purchasesSameSku14d",
    "purchasesSameSku30d",
    "unitsSoldSameSku1d",
    "unitsSoldSameSku7d",
    "unitsSoldSameSku14d",
    "unitsSoldSameSku30d",
    "kindleEditionNormalizedPagesRead14d",
    "kindleEditionNormalizedPagesRoyalties14d",
    "salesOtherSku7d",
    "unitsSoldOtherSku7d",
    "acosClicks7d",
    "acosClicks14d",
    "roasClicks7d",
    "roasClicks14d",
    "keywordId",
    "keyword",
    "campaignBudgetCurrencyCode",
    "portfolioId",
    "campaignName",
    "campaignId",
    "campaignBudgetType",
    "campaignBudgetAmount",
    "campaignStatus",
    "keywordBid",
    "adGroupName",
    "adGroupId",
    "keywordType",
    "matchType",
    "targeting",
    "topOfSearchImpressionShare"
]

export const ADVERTISED_PRODUCT_METRICS = [
    "date",
    "campaignName",
    "campaignId",
    "adGroupName",
    "adGroupId",
    "adId",
    "addToList",
    "qualifiedBorrows",
    "royaltyQualifiedBorrows",
    "portfolioId",
    "impressions",
    "clicks",
    "costPerClick",
    "clickThroughRate",
    "cost",
    "spend",
    "campaignBudgetCurrencyCode",
    "campaignBudgetAmount",
    "campaignBudgetType",
    "campaignStatus",
    "advertisedAsin",
    "advertisedSku",
    "purchases1d",
    "purchases7d",
    "purchases14d",
    "purchases30d",
    "purchasesSameSku1d",
    "purchasesSameSku7d",
    "purchasesSameSku14d",
    "purchasesSameSku30d",
    "unitsSoldClicks1d",
    "unitsSoldClicks7d",
    "unitsSoldClicks14d",
    "unitsSoldClicks30d",
    "sales1d",
    "sales7d",
    "sales14d",
    "sales30d",
    "attributedSalesSameSku1d",
    "attributedSalesSameSku7d",
    "attributedSalesSameSku14d",
    "attributedSalesSameSku30d",
    "salesOtherSku7d",
    "unitsSoldSameSku1d",
    "unitsSoldSameSku7d",
    "unitsSoldSameSku14d",
    "unitsSoldSameSku30d",
    "unitsSoldOtherSku7d",
    "kindleEditionNormalizedPagesRead14d",
    "kindleEditionNormalizedPagesRoyalties14d",
    "acosClicks7d",
    "acosClicks14d",
    "roasClicks7d",
    "roasClicks14d"
]